# Generated by Django 4.2.2 on 2023-06-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
